### PR TITLE
Add convex hull requirements

### PR DESCRIPTION
**Pull request by Doprez**
More work is needed. I think the issue is that Indices arent getting created correctly on custom models. 

The way it works is very simple, It takes the model reference from the entity and gets the verts and indices of the mesh using the MeshExtensions method.
image

### CODE REVIEW

**Comment by Doprez** [comment]
https://discord.com/channels/668192300706430979/668192300706430982/1174176507195817984

Conversation from the lovely bepu community. I will need to look into one of 2 options:
- pass the polygons to BP2
- convex mesh decomposition

decomp definitely sounds like the larger bit of work but seems like the most favourable as well.

**Comment by Nicogo1705** [comment]
https://github.com/DesignEngrLab/MIConvexHull -To aproximate the shape (using ConvexHullCollider)

[The V-HACD](https://github.com/kmammou/v-hacd#the-v-hacd-library-decomposes-a-3d-surface-into-a-set-of-near-convex-parts) -looks like there is a c# wrapper
https://github.com/kmammou/v-hacd -To build multiple ConvexHullCollider from a concave mesh.

hacd need to be ported to c# or used as a lib

**Comment by Doprez** [comment]
Ah sweet CoACD has an example with Unity as well.

https://github.com/SarahWeiii/CoACD/tree/unity/Packages/info.flandre.coacd/Runtime

I will try it out after work!

**Comment by Doprez** [comment]
Just pasting some more options so I dont forget when I have time to work on this.

https://github.com/DigitalRune/DigitalRune/blob/master/Source/DigitalRune.Geometry/GeometryHelper.cs#L157
example:
https://www.youtube.com/watch?v=Y8NxEkvtqw0

**Comment by Doprez** [comment]
So this is mostly done the only thing thats needed is a central BufferPool. I am currently creating a new one for each convex hull which is almost definitely wrong.

I also decided that decomposition can be done in a future larger PR just to make things move along for now.

**Pull request merged**
